
ALTER TABLE "users" 
ADD COLUMN IF NOT EXISTS "email" TEXT UNIQUE,
ADD COLUMN IF NOT EXISTS "name" TEXT,

ADD COLUMN IF NOT EXISTS "google_id" TEXT UNIQUE,
ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP DEFAULT NOW();
